version: "3.7"

services: 
  database_ignite: 
    image: postgres
    container_name: database_ignite
    restart: always
    environment:
      - POSTGRES_USER=docker_rentx_db
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentx
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local